-- ScholarTrack Emergency RLS Fix
-- Run this in Supabase Dashboard → SQL Editor
-- Generated by pentest on 2026-07-16

-- ============================================
-- STEP 1: Enable RLS on ALL tables
-- ============================================
ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE children ENABLE ROW LEVEL SECURITY;
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_contacts ENABLE ROW LEVEL SECURITY;

-- ============================================
-- STEP 2: Drivers policies
-- ============================================
-- Drivers can only see their own profile
CREATE POLICY "drivers_select_own" ON drivers
  FOR SELECT USING (auth.uid() = user_id);

-- Drivers can update their own profile
CREATE POLICY "drivers_update_own" ON drivers
  FOR UPDATE USING (auth.uid() = user_id);

-- Drivers can insert their own profile
CREATE POLICY "drivers_insert_own" ON drivers
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ============================================
-- STEP 3: Children policies
-- ============================================
-- Parents can see their own children
CREATE POLICY "children_select_parent" ON children
  FOR SELECT USING (auth.uid() = parent_id);

-- Parents can add children
CREATE POLICY "children_insert_parent" ON children
  FOR INSERT WITH CHECK (auth.uid() = parent_id);

-- Parents can update their children
CREATE POLICY "children_update_parent" ON children
  FOR UPDATE USING (auth.uid() = parent_id);

-- Parents can remove their children
CREATE POLICY "children_delete_parent" ON children
  FOR DELETE USING (auth.uid() = parent_id);

-- Drivers assigned to a trip can see the child on that trip
CREATE POLICY "children_select_driver" ON children
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM trips
      WHERE trips.child_id = children.id
      AND trips.driver_id IN (
        SELECT id FROM drivers WHERE user_id = auth.uid()
      )
    )
  );

-- ============================================
-- STEP 4: Trips policies
-- ============================================
-- Drivers can see their own trips
CREATE POLICY "trips_select_driver" ON trips
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM drivers WHERE drivers.id = trips.driver_id AND drivers.user_id = auth.uid())
  );

-- Parents can see trips for their children
CREATE POLICY "trips_select_parent" ON trips
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM children WHERE children.id = trips.child_id AND children.parent_id = auth.uid())
  );

-- Drivers can create trips
CREATE POLICY "trips_insert_driver" ON trips
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM drivers WHERE drivers.id = trips.driver_id AND drivers.user_id = auth.uid())
  );

-- Drivers can update their own trips
CREATE POLICY "trips_update_driver" ON trips
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM drivers WHERE drivers.id = trips.driver_id AND drivers.user_id = auth.uid())
  );

-- ============================================
-- STEP 5: Vehicles policies
-- ============================================
CREATE POLICY "vehicles_select_own" ON vehicles
  FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "vehicles_insert_own" ON vehicles
  FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "vehicles_update_own" ON vehicles
  FOR UPDATE USING (auth.uid() = owner_id);

-- ============================================
-- STEP 6: Emergency contacts policies
-- ============================================
CREATE POLICY "emergency_select_own" ON emergency_contacts
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "emergency_insert_own" ON emergency_contacts
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "emergency_update_own" ON emergency_contacts
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "emergency_delete_own" ON emergency_contacts
  FOR DELETE USING (auth.uid() = user_id);
